// <auto-generated />
using System;
using FuncionariosApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuncionariosApp.Migrations
{
    [DbContext(typeof(FuncionarioContext))]
    partial class FuncionarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FuncionariosApp.Models.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2eef0d0-7865-4834-a184-7d914d798440"),
                            Idade = 30,
                            Nome = "Mark",
                            NumeroConta = "123-3452134543-32"
                        },
                        new
                        {
                            Id = new Guid("8e6c3570-7c7d-4534-b44f-954af822e0e2"),
                            Idade = 28,
                            Nome = "Evelin",
                            NumeroConta = "123-9384613085-55"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
